//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaCelsia
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFO
    {
        public string ConnectionDeviceId { get; set; }
        public string EventProcessedUtcTime { get; set; }
        public string HEFESTO_ID { get; set; }
        public string timestamp { get; set; }
        public string var_name { get; set; }
        public int value { get; set; }
        public string plugin { get; set; }
        public string request { get; set; }
        public string var_name_1 { get; set; }
        public byte device { get; set; }
    }
}
